services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-passw0rd}
      --save 60 1
      --loglevel warning
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-passw0rd}
    volumes:
      - redis_data:/data
    networks:
      - redis_net
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-passw0rd}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:

networks:
  redis_net:

