services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-passw0rd}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-dummy}
      MARIADB_USER: ${MARIADB_USER:-admin}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-passw0rd}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_net
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:

networks:
  mariadb_net:
