services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"     # API access
      - "9001:9001"     # Console UI
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-passw0rd}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - minio_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  minio_data:

networks:
  minio_net:
